create TABLE ADDRESS(
	ID INTEGER PRIMARY KEY,
	HOUSENO INTEGER,
);

create TABLE CATEGORY(
	CID INTEGER PRIMARY KEY,
	CATEGORYNAME VARCHAR(30),
);


CREATE TABLE GREETINGS (
  GREETING_ID  INTEGER PRIMARY KEY,
  CONTENT VARCHAR(30),
  PRIORITY	INTEGER,
  TYPE VARCHAR(10),
  ID INTEGER ,
  CID INTEGER ,
  CONSTRAINT t_fk
  FOREIGN KEY (ID)
    REFERENCES ADDRESS,
    CONSTRAINT S_fk
  FOREIGN KEY (CID)
    REFERENCES CATEGORY(CID)
  
);
 
  INSERT INTO ADDRESS VALUES(11,3424);
  INSERT INTO ADDRESS VALUES(12,3428);
  INSERT INTO ADDRESS VALUES(13,3420);
  
  INSERT INTO CATEGORY VALUES(101,'Birthday Wishes');
  INSERT INTO CATEGORY VALUES(102,'Anniversary Wishes');
  INSERT INTO CATEGORY VALUES(103,'Teachers Day Wishes');
    
  
  
INSERT INTO GREETINGS VALUES (1, 'Happy Birthday',5,'GREAT',11,101); 
INSERT INTO GREETINGS VALUES (2, 'Warm Birthday Wishes',1,'OK',11,101);
INSERT INTO GREETINGS VALUES (3, 'Manpreet is good guy',2,'OKOK',12,102);
INSERT INTO GREETINGS VALUES (4, 'kamaljeet is good girl',5,'GREAT',12,102);
INSERT INTO GREETINGS VALUES (5, 'I love Anhad',1,'OK',13,103);
INSERT INTO GREETINGS VALUES (6, 'HaveAGoodDay Mrs Sanders',2,'GREAT',13,103);



	         

	         
